
logging:
  level:
    fun.gatsby: DEBUG

app:
  global-task-config:
    #输入目录
    in-dir-path: D:\原始备份\分類補注李太白詩二十五卷分類編次李太白文五卷-0003
    #输出目录
    out-dir-path: D:\out
    enforce: true

  process-tasks:
    IMAGE_TRANSFORM:
      #输出格式
      format: jpg

    IMAGE_COMPRESS:
      #压缩限制大小
      compress-limit: 500

    DRAW_BLUR:
      blur-image-path: D:\datasets\图片处理模板\2 模糊图

    PDF_MERGE:
      #目录文件所在目录
      cata-dir-path: D:\datasets\图片处理模板\3 目录文件

    IMAGE_CUT:
      label-file-path: D:\datasets\图片处理模板\4 标签文件

    OCR_LABELED_DATASET_XML_GENERATE:
        #目录文件所在目录
        cata-dir-path: D:\datasets\图片处理模板\3 目录文件

    DOULE_LAYER_PDF_GENERATE:
      #目录文件所在目录
      cata-dir-path: D:\datasets\图片处理模板\3 目录文件
    LABELED_DATASET_COLLECT:
      rate-of-train: 0.9

