
logging:
  level:
    fun.gatsby: DEBUG

app:

  global-task-config:
    #输入目录
    in-dir-path: D:\原始备份\图片处理模板\4 PDF\无水印\27030166
    #输出目录
    out-dir-path: D:\out
    enforce: true

  process-tasks:
    IMAGE_TRANSFORM:
      #输出格式
      format: jpg

    IMAGE_COMPRESS:
      #压缩限制大小
      compress-limit: 500
      format: jp2

    DRAW_BLUR:
      blur-image-path: D:\原始备份\图片处理模板\2 模糊图
    PDF_MERGE:
      #目录文件所在目录
      cata-dir-path: D:\原始备份\图片处理模板\3 目录文件
    IMAGE_CUT:
      label-file-path: D:\原始备份\图片处理模板\4 标签文件
    DOUBLE_LAYER_PDF_GENERATE:
      #目录文件所在目录
      cata-dir-path: D:\原始备份\图片处理模板\5 目录
      label-dir-path: D:\原始备份\双层pdf相关\label
    LABELED_DATASET_COLLECT:
      rate-of-train: 0.9
    PDF_ADD_CATA:
      #目录文件所在目录
      cata-dir-path: ${app.global-task-config.in-dir-path}

