
logging:
  level:
    fun.gatsby: DEBUG

app:
  task-to-startup: DS_API_TEST
  global-task-config:
    #输入目录
    in-dir: "/Users/jg/Documents/untitled folder"
    #输出目录
#    out-dir: "/Volumes/影视/media/音频转录/UP主投稿/未明子"
    out-dir: "/Volumes/影视/temp"
    enforce: false
    threads: 4

  process-tasks:
    IMAGE_TRANSFORM:
      #输出格式
      ext: jpg

    JP2_COMPRESS:
      #压缩限制大小
      limit: 500
    SOUNDTRACK_EXTRACT:
      ext: mp3
      timeout: 1200

    DRAW_BLUR:
      blur-image-path: D:/原始备份/图片处理模板/2 模糊图
    PDF_MERGE:
      #目录文件所在目录
      cata-dir-path: D:/原始备份/图片处理模板/5 目录
    PDF_ADD_CATA:
      #目录文件所在目录
      cata-dir-path: ${app.global-task-config.in-dir-path}
    TRANSCRIBE:
      api-url:  https://71df-123-174-48-26.ngrok-free.app/api/transcribe
      timeout: 300
    DS_API_TEST:
      api_key: sk-237d194906e3476fb8249e89ce9366de