
logging:
  level:
    root: info
    fun.gatsby: debug
  file:
    path: logs

spring:
  profiles:
    active: @activated-profile@

app:
  readme-url: "https://www.zybuluo.com/Civin/note/2542177"
  version: @app.version@
  author: JGatsby, Civin@bupt.cn
  name: "图片批处理程序"
  logging-file-path: ${logging.file.path}

  global-task-config:
    #输入目录
    in-dir-path: 请替换为你的输入目录
    #输出目录
    out-dir-path: 请替换为你的输出目录
    #处理线程数
    max-worker-num: 4

    file-name-regex: ^(?!seka).*$ #不以seka开头的文件名

    recursive: true #是否递归处理子目录
  #处理项
  #任务类型 目前只有4重类型：IMAGE_TRANSFORM、IMAGE_COMPRESS、DRAW_BLUR、PDF_MERGE
  process-tasks:

    IMAGE_TRANSFORM:
        #输出格式
      format:

    IMAGE_COMPRESS:
      #压缩限制大小
      compress-limit: 500

    DRAW_BLUR:
      blur-image-path:

    PDF_MERGE:
      #目录文件所在目录
      cata-dir-path:

    IMAGE_CUT:
      label-file-path: