
logging:
  level:
    com.example: warn


app:
  base-dir-path: C:\Users\Gatsby\datasets\1948-02
  base-out-dir-path: ${app.base-dir-path}
  blur-image-path: C:\Users\Gatsby\IdeaProjects\sb-img-util\src\main\resources\blur.png

  process-list:
  - jp2:
      enable: true
      with-blur: false
      compress-limit: 0 #单位kb
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/2 拼图无损JPEG2000
  - jp2:
      enable: true
      with-blur: true
      compress-limit: 500 #单位kb
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/3 水印有损JPEG2000/无水印

  - jp2:
      enable: true
      with-blur: true
      compress-limit: 500 #单位kb
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/3 水印有损JPEG2000/有水印

  - jpg:
      enable: true
      with-blur: false
      compress-limit: 0 #单位kb 0表示不压缩
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/无损JPEG

  - pdf:
      enbale: true
      with-blur: true
      compress-limit: 0 #单位kb 0表示不压缩
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/PDF