
logging:
  file:
    name: ${app.base-out-dir-path}/log.txt

spring:
  profiles:
    active: dev

app:
  tif-dir-path:
  base-out-dir-path:
  pdf-cata-dir-path: ${app.tif-dir-path}/../5 目录
  blur-image-path:
  #处理线程数
  worker-num: 8
  process-list:
  #无损jp2
  - jp2:
      enable: false
      with-blur: false
      compress-limit: 0 #单位kb
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/2 拼图无损JP2000

  #有损jp2无水印
  - jp2:
      enable: false
      with-blur: false
      compress-limit: 500 #单位kb
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/无水印

  #有损jp2有水印
  - jp2:
      enable: false
      with-blur: true
      compress-limit: 500 #单位kb
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/有水印

  #封面
  - jpg:
      enable: false
      with-blur: true
      compress-limit: 0 #单位kb 0表示不压缩
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}\7 提交平台\封面
      file-name-reg: 0001.tif

    #jpg无损
  - jpg:
      enable: false
      with-blur: false
      compress-limit: 0 #单位kb 0表示不压缩
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}\JPG无损

###################################
  #pdf是书籍处理完成后的后置处理
###################################

  #pdf无水印
  - pdf:
      enable: true
      compress-limit: 0 #单位kb 0表示不压缩
      with-blur: false
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/4 PDF/无水印
      resource-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/无水印
      cata-dir-path: ${app.pdf-cata-dir-path}

  #pdf带水印
  - pdf:
      enable: true
      compress-limit: 0 #单位kb 0表示不压缩
      with-blur: false
      blur-image-path: ${app.blur-image-path}
      out-dir-path: ${app.base-out-dir-path}/4 PDF/有水印
      resource-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/有水印
      cata-dir-path: ${app.pdf-cata-dir-path}