
logging:
  file:
    name: ${app.base-out-dir-path}/log.txt

#spring:
#  profiles:
#    active: dev

app:
  base-in-dir-path: /Users/gatsby/IdeaProjects/sb-img-util/src/main/resources
  base-out-dir-path: output
  blur-image-path: /Users/gatsby/IdeaProjects/sb-img-util/src/main/resources\blur.png
  #处理线程数
  max-worker-num: 8
  process-tasks:
    IT1:
      task-type: IMAGE_TRANSFORM
      enable: true
      out-dir-path: ${app.base-out-dir-path}/2 JP2000无损
      in-dir-path: ${app.base-in-dir-path}
      file-name-regex: ^(?!seka).*$ #不以seka开头的文件名
      format: jpg
      depend-on:

#    DB1:
#      task-type: DRAW-BLUR
#      enable: true
#      out-dir-path: ${app.base-out-dir-path}/4 PDF/有水印
#      in-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/有水印
#      file-name-regex: ^(?!seka).*$ #不以seka开头的文件名
#      blur-image-path: ${app.blur-image-path}
#      depend-on: 1
#
#    IC1:
#      task-type: IMAGE-COMPRESS
#      enable: true
#      out-dir-path: ${app.base-out-dir-path}/4 PDF/有水印
#      in-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/有水印
#      file-name-regex: ^(?!seka).*$ #不以seka开头的文件名
#      compress-limit: 500
#      depend-on: 2
#
#    IC2:
#      task-type: IMAGE-COMPRESS
#      enable: true
#      out-dir-path: ${app.base-out-dir-path}/4 PDF/有水印
#      in-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/有水印
#      file-name-regex: ^(?!seka).*$ #不以seka开头的文件名
#      compress-limit: 500
#      depend-on: 2
#
#    PM1:
#      task-type: PDF-MERGE
#      enable: true
#      out-dir-path: ${app.base-out-dir-path}/4 PDF/有水印
#      in-dir-path: ${app.base-out-dir-path}/3 水印有损JP2000/有水印
#      file-name-regex: ^(?!seka).*$ #不以seka开头的文件名
#      cata-dir-path: ${app.cata-dir-path}
#      depend-on: 2

