
logging:
  level:
    root: info
    fun.gatsby: info
  file:
    path: logs

spring:
  devtools:
    livereload:
      enabled: false
  profiles:
    active: @activated-profile@

app:
  readme-url: "https://www.zybuluo.com/Civin/note/2542177"
  version: @app.version@
  author: JGatsby, Civin@bupt.cn
  name: "图片批处理程序"
  logging-file-path: ${logging.file.path}

  global-task-config:
    #输入目录
    in-dir-path: 请替换为你的输入目录
    #输出目录
    out-dir-path: 请替换为你的输出目录
    #处理线程数
    max-worker-num: 4

    file-name-regex: ^(?!seka).*$ #不以seka开头的文件名

    recursive: true #是否递归处理子目录
    enforce: false #是否强制覆盖已存在的文件
  #处理项
  #任务类型 目前只有4重类型：IMAGE_TRANSFORM、IMAGE_COMPRESS、DRAW_BLUR、PDF_MERGE
  process-tasks:
    IMAGE_TRANSFORM:
      #输出格式
      format: jpg

    IMAGE_COMPRESS:
      #压缩限制大小
      compress-limit: 500
      format: jp2

    DRAW_BLUR:
      blur-image-path:
    PDF_MERGE:
      #目录文件所在目录
      cata-dir-path:
    IMAGE_CUT:
      label-file-path:
    DOUBLE_LAYER_PDF_GENERATE:
      #目录文件所在目录
      cata-dir-path:
      label-dir-path:
    LABELED_DATASET_COLLECT:
      rate-of-train: 0.9
    PDF_ADD_CATA:
      #目录文件所在目录
      cata-dir-path:
