
logging:
  level:
    fun.gatsby: DEBUG

app:
  task-to-startup: PDF_SPLIT
  global-task-config:
    #输入目录
    in-dir: "E:/OneDrive/桌面/New folder"
    #输出目录
    out-dir: "E:/OneDrive/桌面/"
    enforce: false
    threads: 4

  task-config-map:
    IMAGE_TRANSFORM:
      #输出格式
      ext: jpg

    JP2_COMPRESS:
      #压缩限制大小
      limit: 500
    SOUNDTRACK_EXTRACT:
      ext: mp3
      timeout: 1200

    DRAW_BLUR:
      blur-image-path: D:/原始备份/图片处理模板/2 模糊图
    PDF_MERGE:
      #目录文件所在目录
      cata-dir-path: D:/原始备份/图片处理模板/5 目录
    PDF_ADD_CATA:
      #目录文件所在目录
      cata-dir-path: ${app.global-task-config.in-dir-path}
    TRANSCRIBE:
      api-url:  https://71df-123-174-48-26.ngrok-free.app/api/transcribe
      timeout: 300
    CHAT_API:
      api-key: sk-237d194906e3476fb8249e89ce9366de